"""WP-E1 (Option B) — log-infrastructure settings: LOG_LEVEL, LOG_BACKEND, LOG_GROUP.

Tests verify that:
  1. LOG_LEVEL default is ``info``.
  2. LOG_LEVEL=debug overrides the global default for rules without a
     per-rule level.
  3. Per-rule log_level beats the global LOG_LEVEL.
  4. LOG_BACKEND=netlink emits ``log group N`` instead of ``log … level …``.
  5. LOG_BACKEND=NFLOG (upper-case) is treated the same as netlink.
  6. LOG_BACKEND=ULOG is a legacy alias for netlink.
  7. An unknown LOG_BACKEND value raises ValueError at build_ir() time.
  8. LOG_BACKEND=netlink without explicit LOG_GROUP defaults to group 1.
  9. A non-integer LOG_GROUP raises ValueError at build_ir() time.

All tests are string-level (no kernel calls).  The minimal fixture is
used where a full compile pipeline is needed; direct IR construction is
used for pure emit-level assertions.
"""

from __future__ import annotations

import pytest

from shorewall_nft.compiler.ir import (
    Chain,
    ChainType,
    FirewallIR,
    Rule,
    Verdict,
)
from shorewall_nft.compiler.ir import build_ir
from shorewall_nft.compiler.verdicts import NflogVerdict
from shorewall_nft.config.parser import load_config
from shorewall_nft.nft.emitter import _log_settings_from_ir, emit_nft

from pathlib import Path

MINIMAL_DIR = Path(__file__).parent / "configs" / "minimal"


# ── helpers ──────────────────────────────────────────────────────────────────


def _ir_with_log_rule(
    log_level: str | None = None,
    log_prefix: str = "TEST",
    *,
    ir_settings: dict[str, str] | None = None,
) -> FirewallIR:
    """Return a bare FirewallIR with one LOG rule in a non-base chain."""
    ir = FirewallIR()
    if ir_settings:
        ir.settings.update(ir_settings)
    ch = Chain(name="loc-fw", chain_type=ChainType.FILTER)
    rule = Rule(verdict=Verdict.LOG, log_level=log_level, log_prefix=log_prefix)
    ch.rules.append(rule)
    ir.chains["loc-fw"] = ch
    return ir


def _emit(**settings: str) -> str:
    """Load minimal config, override settings, compile, emit."""
    config = load_config(MINIMAL_DIR)
    config.settings.update(settings)
    ir = build_ir(config)
    return emit_nft(ir)


# ── 1. default level ─────────────────────────────────────────────────────────


class TestLogLevelDefault:
    """No LOG_LEVEL setting → emitted level defaults to 'info'."""

    def test_log_level_default(self):
        ir = _ir_with_log_rule(log_level=None)
        out = emit_nft(ir)
        assert "level info" in out

    def test_log_level_default_no_setting_in_ir(self):
        """No LOG_LEVEL in ir.settings → defaults to info."""
        ir = _ir_with_log_rule(log_level=None, ir_settings={})
        ls = _log_settings_from_ir(ir)
        assert ls.default_level == "info"
        assert ls.backend == "LOG"

    def test_log_settings_from_ir_defaults(self):
        ir = FirewallIR()
        ls = _log_settings_from_ir(ir)
        assert ls.backend == "LOG"
        assert ls.default_level == "info"
        assert ls.group == 1


# ── 2. global LOG_LEVEL override ─────────────────────────────────────────────


class TestLogLevelGlobalOverride:
    """LOG_LEVEL=debug → rules without per-rule level use 'debug'."""

    def test_global_level_in_log_settings(self):
        ir = FirewallIR()
        ir.settings["LOG_LEVEL"] = "debug"
        ls = _log_settings_from_ir(ir)
        assert ls.default_level == "debug"

    def test_global_level_in_emitted_rule(self):
        """When LOG_LEVEL=debug, a rule with no per-rule level emits 'debug'."""
        ir = _ir_with_log_rule(log_level=None, ir_settings={"LOG_LEVEL": "debug"})
        out = emit_nft(ir)
        assert "level debug" in out

    def test_global_level_invalid_falls_back_to_info(self):
        """An unrecognised LOG_LEVEL string falls back to 'info' in emit."""
        ir = _ir_with_log_rule(log_level=None, ir_settings={"LOG_LEVEL": "notlevel"})
        ls = _log_settings_from_ir(ir)
        # _log_settings_from_ir normalises to "info" when level is unknown.
        assert ls.default_level == "info"

    def test_global_level_via_full_pipeline(self):
        out = _emit(LOG_LEVEL="debug")
        # The minimal config has no LOG rules so we check settings are
        # accepted without error.  A full-pipeline check for the emitted
        # fragment requires a LOG rule in the config — verified by the
        # direct-IR tests above.
        assert "Generated by shorewall-nft" in out


# ── 3. per-rule log_level wins over global ───────────────────────────────────


class TestLogLevelPerRuleWins:
    """Per-rule log_level beats the global LOG_LEVEL setting."""

    def test_per_rule_overrides_global(self):
        ir = _ir_with_log_rule(
            log_level="warn",
            ir_settings={"LOG_LEVEL": "debug"},
        )
        out = emit_nft(ir)
        assert "level warn" in out
        assert "level debug" not in out

    def test_per_rule_strip_limit_tag(self):
        """'info:LOGIN,12,60' → level 'info' (strips the rate-limit tag)."""
        ir = _ir_with_log_rule(
            log_level="info:LOGIN,12,60",
            ir_settings={"LOG_LEVEL": "debug"},
        )
        out = emit_nft(ir)
        assert "level info" in out
        assert "level debug" not in out

    def test_per_rule_notice_overrides_info_default(self):
        ir = _ir_with_log_rule(log_level="notice")
        out = emit_nft(ir)
        assert "level notice" in out


# ── 4. LOG_BACKEND=netlink ───────────────────────────────────────────────────


class TestLogBackendNetlink:
    """LOG_BACKEND=netlink → emits 'log group N', not 'level ...'."""

    def test_netlink_backend_emits_log_group(self):
        ir = _ir_with_log_rule(
            log_level=None,
            ir_settings={"LOG_BACKEND": "netlink", "LOG_GROUP": "3"},
        )
        out = emit_nft(ir)
        assert "log group 3" in out
        assert "level" not in out

    def test_netlink_backend_no_prefix_in_fragment(self):
        """nft 'log group N' has no prefix string."""
        ir = _ir_with_log_rule(
            log_level=None,
            log_prefix="MYPFX",
            ir_settings={"LOG_BACKEND": "netlink", "LOG_GROUP": "5"},
        )
        out = emit_nft(ir)
        assert "log group 5" in out
        # Prefix is intentionally absent for the netlink backend.
        assert "MYPFX" not in out

    def test_netlink_normalised_in_log_settings(self):
        ir = FirewallIR()
        ir.settings["LOG_BACKEND"] = "netlink"
        ir.settings["LOG_GROUP"] = "3"
        ls = _log_settings_from_ir(ir)
        assert ls.backend == "netlink"
        assert ls.group == 3


# ── 5. LOG_BACKEND=NFLOG alias ───────────────────────────────────────────────


class TestLogBackendNflogAlias:
    """LOG_BACKEND=NFLOG (and nflog) is an alias for netlink."""

    @pytest.mark.parametrize("value", ["NFLOG", "nflog", "Nflog"])
    def test_nflog_treated_as_netlink(self, value):
        ir = FirewallIR()
        ir.settings["LOG_BACKEND"] = value
        ls = _log_settings_from_ir(ir)
        assert ls.backend == "netlink"

    def test_nflog_emits_log_group(self):
        ir = _ir_with_log_rule(
            log_level=None,
            ir_settings={"LOG_BACKEND": "NFLOG", "LOG_GROUP": "2"},
        )
        out = emit_nft(ir)
        assert "log group 2" in out
        assert "level" not in out


# ── 6. LOG_BACKEND=ULOG alias ────────────────────────────────────────────────


class TestLogBackendUlogAlias:
    """LOG_BACKEND=ULOG is a legacy alias for the netlink path."""

    @pytest.mark.parametrize("value", ["ULOG", "ulog"])
    def test_ulog_treated_as_netlink(self, value):
        ir = FirewallIR()
        ir.settings["LOG_BACKEND"] = value
        ls = _log_settings_from_ir(ir)
        assert ls.backend == "netlink"

    def test_ulog_emits_log_group(self):
        ir = _ir_with_log_rule(
            log_level=None,
            ir_settings={"LOG_BACKEND": "ULOG", "LOG_GROUP": "7"},
        )
        out = emit_nft(ir)
        assert "log group 7" in out
        assert "level" not in out


# ── 7. unknown LOG_BACKEND raises at build_ir time ───────────────────────────


class TestLogBackendUnknownRaises:
    """An unrecognised LOG_BACKEND value raises ValueError at build_ir()."""

    def test_unknown_backend_raises(self):
        config = load_config(MINIMAL_DIR)
        config.settings["LOG_BACKEND"] = "invalid"
        with pytest.raises(ValueError, match="invalid"):
            build_ir(config)

    def test_error_message_names_accepted_values(self):
        config = load_config(MINIMAL_DIR)
        config.settings["LOG_BACKEND"] = "IPTABLES"
        with pytest.raises(ValueError) as exc_info:
            build_ir(config)
        msg = str(exc_info.value)
        assert "IPTABLES" in msg
        # Message should hint at valid values.
        assert "LOG" in msg

    @pytest.mark.parametrize("bad", ["syslog", "kernel", "", "  "])
    def test_various_bad_backends(self, bad):
        config = load_config(MINIMAL_DIR)
        config.settings["LOG_BACKEND"] = bad
        with pytest.raises(ValueError):
            build_ir(config)


# ── 8. LOG_GROUP default is 1 ────────────────────────────────────────────────


class TestLogGroupDefault:
    """When LOG_BACKEND=netlink and LOG_GROUP is absent, group defaults to 1."""

    def test_default_group_is_1(self):
        ir = FirewallIR()
        ir.settings["LOG_BACKEND"] = "netlink"
        # No LOG_GROUP set.
        ls = _log_settings_from_ir(ir)
        assert ls.group == 1

    def test_default_group_emitted_as_1(self):
        ir = _ir_with_log_rule(
            log_level=None,
            ir_settings={"LOG_BACKEND": "netlink"},
        )
        out = emit_nft(ir)
        assert "log group 1" in out

    def test_default_group_via_pipeline(self):
        config = load_config(MINIMAL_DIR)
        config.settings["LOG_BACKEND"] = "netlink"
        # Must not raise; LOG_GROUP absent defaults to 1.
        ir = build_ir(config)
        ls = _log_settings_from_ir(ir)
        assert ls.group == 1


# ── 9. non-integer LOG_GROUP raises at build_ir time ─────────────────────────


class TestLogGroupParseError:
    """A non-integer LOG_GROUP raises ValueError at build_ir() time."""

    def test_non_integer_group_raises(self):
        config = load_config(MINIMAL_DIR)
        config.settings["LOG_GROUP"] = "notanint"
        with pytest.raises(ValueError, match="notanint"):
            build_ir(config)

    def test_float_group_raises(self):
        config = load_config(MINIMAL_DIR)
        config.settings["LOG_GROUP"] = "1.5"
        with pytest.raises(ValueError):
            build_ir(config)

    def test_empty_group_raises(self):
        config = load_config(MINIMAL_DIR)
        config.settings["LOG_GROUP"] = ""
        with pytest.raises(ValueError):
            build_ir(config)


# ── NflogVerdict typed path uses group field ─────────────────────────────────


class TestNflogVerdictGroupField:
    """NflogVerdict.group is used by the typed-verdict emitter."""

    def test_nflog_verdict_default_group_zero(self):
        v = NflogVerdict()
        assert v.group == 0

    def test_nflog_verdict_custom_group(self):
        v = NflogVerdict(group=5)
        assert v.group == 5

    def test_nflog_verdict_emits_correct_group(self):
        """Rule with NflogVerdict(group=9) should emit 'log group 9'."""
        ir = FirewallIR()
        ch = Chain(name="test-chain", chain_type=ChainType.FILTER)
        rule = Rule(verdict=Verdict.LOG, verdict_args=NflogVerdict(group=9))
        ch.rules.append(rule)
        ir.chains["test-chain"] = ch
        out = emit_nft(ir)
        assert "log group 9" in out


# ---------------------------------------------------------------------------
# Option C — LOGFORMAT / MAXZONENAMELENGTH (LOGRULENUMBERS is parsed only)
# ---------------------------------------------------------------------------


class TestLogFormat:
    """LOGFORMAT + MAXZONENAMELENGTH apply at compile time to log_prefix."""

    def _settings(self, **kw):
        from shorewall_nft.nft.emitter import LogSettings, _log_settings_from_ir
        ir = FirewallIR(settings=kw)
        return _log_settings_from_ir(ir), LogSettings

    def test_default_template(self):
        s, _ = self._settings()
        assert s.format_prefix("net-loc", "drop") == "Shorewall:net-loc:DROP:"

    def test_disables_truncation_when_length_0(self):
        s, _ = self._settings(MAXZONENAMELENGTH="0")
        assert s.format_prefix("internal-loc", "accept") == \
            "Shorewall:internal-loc:ACCEPT:"

    def test_honors_max_zone_name_length(self):
        s, _ = self._settings(MAXZONENAMELENGTH="3")
        assert s.format_prefix("internal-loc", "drop") == \
            "Shorewall:int-loc:DROP:"

    def test_custom_logformat(self):
        s, _ = self._settings(LOGFORMAT="fw[%s][%s]:")
        assert s.format_prefix("net-loc", "reject") == "fw[net-loc][REJECT]:"

    def test_non_zone_chain_untouched(self):
        s, _ = self._settings()
        assert s.format_prefix("blacklist", "drop") == "Shorewall:blacklist:DROP:"

    def test_broken_logformat_falls_back(self):
        # Only one %s slot → formatting raises, fallback template is used.
        s, _ = self._settings(LOGFORMAT="only-one:%s:")
        assert s.format_prefix("net-loc", "drop") == "Shorewall:net-loc:DROP:"

    def test_logrulenumbers_parsed(self):
        s, _ = self._settings(LOGRULENUMBERS="Yes")
        assert s.rule_numbers is True
        # NOT yet wired into format_prefix — parsing only.
        assert s.format_prefix("net-loc", "drop") == "Shorewall:net-loc:DROP:"

    def test_invalid_maxzonenamelength_falls_back(self):
        s, _ = self._settings(MAXZONENAMELENGTH="notanint")
        assert s.max_zone_name_length == 5

    def test_negative_maxzonenamelength_clamped_to_zero(self):
        s, _ = self._settings(MAXZONENAMELENGTH="-4")
        assert s.max_zone_name_length == 0
