"""Generate a conntrackd.conf fragment for an HA firewall pair.

Derives the conntrack sync configuration from the shorewall-nft
config: interfaces (for the sync link), CT_ZONE_TAG_MASK (so
zone bits are replicated without leaking unrelated routing marks),
and optional SYNPROXY / FLOWTABLE settings.

The output is a conntrackd.conf fragment, not a full file — the
operator is expected to concat it into their conntrackd.conf or
to use an `Include` directive. This keeps shorewall-nft out of
the business of managing the full conntrackd surface.
"""

from __future__ import annotations

from shorewall_nft.config.parser import ShorewalConfig


def generate_conntrackd_fragment(
    config: ShorewalConfig,
    *,
    sync_iface: str | None = None,
    peer_ip: str | None = None,
    local_ip: str | None = None,
    cluster_ip: str | None = None,
) -> str:
    """Render a conntrackd.conf fragment.

    Args:
        config: parsed shorewall-nft FirewallConfig
        sync_iface: interface used for the conntrackd sync link
            (defaults to "CONNTRACKD_IFACE" setting if present)
        peer_ip: IP address of the other HA node
        local_ip: IP address of this node on the sync link
        cluster_ip: shared VIP that failover moves
    """
    settings = config.settings

    sync_iface = sync_iface or settings.get("CONNTRACKD_IFACE", "eth-sync")
    peer_ip = peer_ip or settings.get("CONNTRACKD_PEER_IP", "192.0.2.2")
    local_ip = local_ip or settings.get("CONNTRACKD_LOCAL_IP", "192.0.2.1")
    cluster_ip = cluster_ip or settings.get("CONNTRACKD_CLUSTER_IP", "192.0.2.100")

    # Zone-tag mask lives on ct mark and MUST be replicated so zones
    # survive failover. Clamp to 32-bit so the arithmetic is sane.
    try:
        zone_mask = int(settings.get("CT_ZONE_TAG_MASK", "0xff"), 0)
    except ValueError:
        zone_mask = 0xff
    zone_mask &= 0xffffffff

    ct_zone_tag = settings.get("CT_ZONE_TAG", "No").lower() in ("yes", "1", "true")

    # Replication filter: when CT_ZONE_TAG is on, sync only marks that
    # intersect zone_mask — this guarantees zones are replicated
    # without dragging routing/policy marks over the sync link.
    if ct_zone_tag and zone_mask:
        mark_filter = f"""    Filter From Kernelspace {{
        Protocol Accept {{
            TCP
            UDP
            ICMP
            SCTP
        }}
        Mark {{
            # Replicate only marks that touch the zone mask
            Value {zone_mask:#010x}
            Mask {zone_mask:#010x}
        }}
    }}"""
    else:
        mark_filter = """    Filter From Kernelspace {
        Protocol Accept {
            TCP
            UDP
            ICMP
            SCTP
        }
    }"""

    lines = [
        "# conntrackd fragment generated by shorewall-nft.",
        "# Concatenate into /etc/conntrackd/conntrackd.conf or Include it.",
        "# Regenerate with: shorewall-nft generate-conntrackd",
        "",
        "Sync {",
        "    Mode FTFW {",
        "        DisableExternalCache Off",
        "        CommitTimeout 1800",
        "        PurgeTimeout 5",
        "    }",
        "",
        "    Multicast Default {",
        "        IPv4_address 225.0.0.50",
        f"        IPv4_interface {local_ip}",
        "        Group 3780",
        f"        Interface {sync_iface}",
        "        SndSocketBuffer 1249280",
        "        RcvSocketBuffer 1249280",
        "        Checksum on",
        "    }",
        "}",
        "",
        "General {",
        "    Nice -20",
        "    HashSize 32768",
        "    HashLimit 262144",
        "    LogFile on",
        "    Syslog on",
        "    LockFile /var/lock/conntrack.lock",
        "    UNIX {",
        "        Path /var/run/conntrackd.ctl",
        "        Backlog 20",
        "    }",
        "    NetlinkBufferSize 2097152",
        "    NetlinkBufferSizeMaxGrowth 8388608",
        "    NetlinkOverrunResync On",
        "    NetlinkEventsReliable Off",
        mark_filter,
        "    Event {",
        "        Reliable Off",
        "    }",
        "}",
        "",
    ]

    if cluster_ip:
        lines.extend([
            "# Active/passive failover — trigger via keepalived notify hook:",
            "#   notify_master \"/usr/sbin/conntrackd -n && /usr/sbin/conntrackd -c\"",
            "#   notify_backup \"/usr/sbin/conntrackd -t\"",
            "#   notify_fault  \"/usr/sbin/conntrackd -t\"",
            "",
        ])

    return "\n".join(lines)
