"""Sysctl script generation from Shorewall configuration.

Translates global settings (``shorewall.conf``) and per-interface options
(``interfaces`` file) into a POSIX shell script that applies the
corresponding ``sysctl -w`` settings.

Inputs: a ``ShorewalConfig`` object produced by
``shorewall_nft.config.parser.load_config`` — specifically its
``settings`` dict (global shorewall.conf keys) and its ``interfaces``
section (parsed by ``build_zone_model``).

Outputs: a single ``str`` containing a standalone ``#!/bin/sh`` script
whose only side-effects are ``sysctl -w`` invocations.  The script
contains no conditionals and is idempotent — re-running it is safe.

Entry point: ``generate_sysctl_script(config) -> str``.
"""

from __future__ import annotations

from shorewall_nft.config.parser import ShorewalConfig
from shorewall_nft.config.zones import build_zone_model
from shorewall_nft.runtime.pyroute2_helpers import settings_bool


def generate_sysctl_script(config: ShorewalConfig) -> str:
    """Generate a shell script to apply sysctl settings."""
    lines: list[str] = []
    lines.append("#!/bin/sh")
    lines.append("# Generated by shorewall-nft — sysctl configuration")
    lines.append("# Run with root privileges")
    lines.append("")

    settings = config.settings

    # IP forwarding
    if settings.get("IP_FORWARDING", "").lower() in ("on", "yes", "1"):
        lines.append("# Enable IP forwarding")
        lines.append("sysctl -w net.ipv4.ip_forward=1")
        lines.append("")

    # Route filter (reverse path filtering)
    if settings_bool(settings, "ROUTE_FILTER", False):
        lines.append("# Enable reverse path filtering (global)")
        lines.append("sysctl -w net.ipv4.conf.all.rp_filter=1")
        lines.append("sysctl -w net.ipv4.conf.default.rp_filter=1")
        lines.append("")

    # Log martians
    if settings_bool(settings, "LOG_MARTIANS", False):
        lines.append("# Log martian packets (global)")
        lines.append("sysctl -w net.ipv4.conf.all.log_martians=1")
        lines.append("sysctl -w net.ipv4.conf.default.log_martians=1")
        lines.append("")

    # Clamp MSS
    if settings_bool(settings, "CLAMPMSS", False):
        lines.append("# Note: MSS clamping handled via nft rules")
        lines.append("")

    # Per-interface settings from interface options
    zones = build_zone_model(config)
    per_iface_v4: dict[str, dict[str, str]] = {}  # net.ipv4.conf.<iface>.*
    per_iface_v6: dict[str, dict[str, str]] = {}  # net.ipv6.conf.<iface>.*

    for zone in zones.zones.values():
        for iface in zone.interfaces:
            opts = set(iface.options)
            oval = iface.option_values  # key=value pairs already parsed
            iface_name = iface.name
            if iface_name not in per_iface_v4:
                per_iface_v4[iface_name] = {}
            if iface_name not in per_iface_v6:
                per_iface_v6[iface_name] = {}

            v4 = per_iface_v4[iface_name]
            v6 = per_iface_v6[iface_name]

            # routefilter → rp_filter, mirroring Shorewall:
            #   routefilter         → 1 (strict)
            #   routefilter=1       → 1 (strict, explicit)
            #   routefilter=2       → 2 (loose)
            #   noroutefilter / routefilter=0 → 0 (off)
            if "routefilter" in oval:
                val = oval["routefilter"]
                if val in ("0", "1", "2"):
                    v4["rp_filter"] = val
            elif "routefilter" in opts:
                v4["rp_filter"] = "1"
            if "noroutefilter" in opts:
                v4["rp_filter"] = "0"

            # logmartians → log_martians
            if "logmartians" in oval:
                v4["log_martians"] = oval["logmartians"]
            elif "logmartians" in opts:
                v4["log_martians"] = "1"

            # arp_filter
            if "arp_filter" in oval:
                v4["arp_filter"] = oval["arp_filter"]
            elif "arp_filter" in opts:
                v4["arp_filter"] = "1"

            # arp_ignore (values 1-3, 8 per upstream)
            if "arp_ignore" in oval:
                v4["arp_ignore"] = oval["arp_ignore"]

            # sourceroute → accept_source_route
            if "sourceroute" in oval:
                v4["accept_source_route"] = oval["sourceroute"]
            elif "sourceroute" in opts:
                v4["accept_source_route"] = "1"

            # proxyarp → proxy_arp
            if "proxyarp" in oval:
                v4["proxy_arp"] = oval["proxyarp"]
            elif "proxyarp" in opts:
                v4["proxy_arp"] = "1"

            # forward → forwarding (IPv4)
            if "forward" in oval:
                v4["forwarding"] = oval["forward"]
            elif "forward" in opts:
                v4["forwarding"] = "1"

            # accept_ra → IPv6 accept_ra
            if "accept_ra" in oval:
                v6["accept_ra"] = oval["accept_ra"]
            elif "accept_ra" in opts:
                v6["accept_ra"] = "1"

    if per_iface_v4:
        has_content = any(p for p in per_iface_v4.values())
        if has_content:
            lines.append("# Per-interface IPv4 settings")
            for iface_name, params in sorted(per_iface_v4.items()):
                if not params:
                    continue
                for param, value in sorted(params.items()):
                    # Dots in interface names become slashes in /proc paths
                    sysctl_iface = iface_name.replace(".", "/")
                    lines.append(
                        f"printf '%s\\n' {value!r} "
                        f"> /proc/sys/net/ipv4/conf/{sysctl_iface}/{param}"
                    )
            lines.append("")

    if per_iface_v6:
        has_content = any(p for p in per_iface_v6.values())
        if has_content:
            lines.append("# Per-interface IPv6 settings")
            for iface_name, params in sorted(per_iface_v6.items()):
                if not params:
                    continue
                for param, value in sorted(params.items()):
                    sysctl_iface = iface_name.replace(".", "/")
                    lines.append(
                        f"printf '%s\\n' {value!r} "
                        f"> /proc/sys/net/ipv6/conf/{sysctl_iface}/{param}"
                    )
            lines.append("")

    # Conntrack
    nf_conntrack_max = settings.get("CONNTRACK_MAX", "")
    if nf_conntrack_max:
        lines.append(f"sysctl -w net.nf_conntrack_max={nf_conntrack_max}")
        lines.append("")

    return "\n".join(lines)
