"""Sysctl script generation from Shorewall configuration.

Translates global settings (``shorewall.conf``) and per-interface options
(``interfaces`` file) into a POSIX shell script that applies the
corresponding ``sysctl -w`` settings.

Inputs: a ``ShorewalConfig`` object produced by
``shorewall_nft.config.parser.load_config`` — specifically its
``settings`` dict (global shorewall.conf keys) and its ``interfaces``
section (parsed by ``build_zone_model``).

Outputs: a single ``str`` containing a standalone ``#!/bin/sh`` script
whose only side-effects are ``sysctl -w`` invocations.  The script
contains no conditionals and is idempotent — re-running it is safe.

Entry point: ``generate_sysctl_script(config) -> str``.
"""

from __future__ import annotations

from shorewall_nft.config.parser import ShorewalConfig
from shorewall_nft.config.zones import build_zone_model


def generate_sysctl_script(config: ShorewalConfig) -> str:
    """Generate a shell script to apply sysctl settings."""
    lines: list[str] = []
    lines.append("#!/bin/sh")
    lines.append("# Generated by shorewall-nft — sysctl configuration")
    lines.append("# Run with root privileges")
    lines.append("")

    settings = config.settings

    # IP forwarding
    if settings.get("IP_FORWARDING", "").lower() in ("on", "yes", "1"):
        lines.append("# Enable IP forwarding")
        lines.append("sysctl -w net.ipv4.ip_forward=1")
        lines.append("")

    # Route filter (reverse path filtering)
    if settings.get("ROUTE_FILTER", "").lower() in ("yes", "1"):
        lines.append("# Enable reverse path filtering (global)")
        lines.append("sysctl -w net.ipv4.conf.all.rp_filter=1")
        lines.append("sysctl -w net.ipv4.conf.default.rp_filter=1")
        lines.append("")

    # Log martians
    if settings.get("LOG_MARTIANS", "").lower() in ("yes", "1"):
        lines.append("# Log martian packets (global)")
        lines.append("sysctl -w net.ipv4.conf.all.log_martians=1")
        lines.append("sysctl -w net.ipv4.conf.default.log_martians=1")
        lines.append("")

    # Clamp MSS
    if settings.get("CLAMPMSS", "").lower() in ("yes", "1"):
        lines.append("# Note: MSS clamping handled via nft rules")
        lines.append("")

    # Per-interface settings from interface options
    zones = build_zone_model(config)
    per_iface: dict[str, dict[str, str]] = {}

    for zone in zones.zones.values():
        for iface in zone.interfaces:
            opts = set(iface.options)
            iface_name = iface.name
            if iface_name not in per_iface:
                per_iface[iface_name] = {}

            # routefilter → rp_filter, mirroring Shorewall:
            #   routefilter         → 1 (strict)
            #   routefilter=1       → 1 (strict, explicit)
            #   routefilter=2       → 2 (loose)
            #   noroutefilter       → 0 (off)
            for opt in opts:
                if opt == "routefilter":
                    per_iface[iface_name]["rp_filter"] = "1"
                elif opt.startswith("routefilter="):
                    val = opt.split("=", 1)[1].strip() or "1"
                    if val in ("0", "1", "2"):
                        per_iface[iface_name]["rp_filter"] = val
            if "noroutefilter" in opts:
                per_iface[iface_name]["rp_filter"] = "0"

            # logmartians
            for opt in opts:
                if opt.startswith("logmartians"):
                    if "=" in opt:
                        val = opt.split("=")[1]
                        per_iface[iface_name]["log_martians"] = val
                    else:
                        per_iface[iface_name]["log_martians"] = "1"

            # arp_filter
            if "arp_filter" in opts:
                per_iface[iface_name]["arp_filter"] = "1"

    if per_iface:
        lines.append("# Per-interface settings")
        for iface_name, params in sorted(per_iface.items()):
            for param, value in sorted(params.items()):
                # Use the interface name without dots for sysctl path
                sysctl_iface = iface_name.replace(".", "/")
                lines.append(f"sysctl -w net.ipv4.conf.{sysctl_iface}.{param}={value}")
        lines.append("")

    # Conntrack
    nf_conntrack_max = settings.get("CONNTRACK_MAX", "")
    if nf_conntrack_max:
        lines.append(f"sysctl -w net.nf_conntrack_max={nf_conntrack_max}")
        lines.append("")

    return "\n".join(lines)
