"""Traffic Control / Mangle rule processing.

Handles:
- MARK, CONNMARK actions and tcrules/mangle files
- tcdevices, tcinterfaces, tcclasses, tcfilters, tcpri configs
- Translates to nft meta mark set / ct mark set statements

Note: nftables does not do tc/qdisc directly. TC shaping is handled
by setting marks in nft which are then used by tc qdiscs configured
separately. The tcdevices/tcclasses/tcfilters configs generate the
corresponding `tc` commands, not nft rules.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from shorewall_nft.compiler.ir import (
    Chain,
    ChainType,
    FirewallIR,
    Hook,
    Match,
    Rule,
    Verdict,
)
from shorewall_nft.config.parser import ConfigLine
from shorewall_nft.config.zones import ZoneModel


@dataclass
class TcDevice:
    """A traffic-controlled device."""
    interface: str
    in_bandwidth: str = ""
    out_bandwidth: str = ""
    options: list[str] = field(default_factory=list)
    redirect: str = ""


@dataclass
class TcClass:
    """A traffic class with rate/ceiling."""
    interface: str
    mark: int
    rate: str
    ceil: str = ""
    priority: int = 1
    options: list[str] = field(default_factory=list)


@dataclass
class TcFilter:
    """A filter to classify traffic into a TC class."""
    tc_class: str  # CLASS reference
    source: str = "-"
    dest: str = "-"
    proto: str = "-"
    dport: str = "-"
    sport: str = "-"
    tos: str = "-"
    length: str = "-"


@dataclass
class TcConfig:
    """Complete TC configuration."""
    devices: list[TcDevice] = field(default_factory=list)
    classes: list[TcClass] = field(default_factory=list)
    filters: list[TcFilter] = field(default_factory=list)


def parse_tc_config(config) -> TcConfig:
    """Parse TC config files into a TcConfig."""
    tc = TcConfig()

    for line in config.tcdevices:
        cols = line.columns
        if len(cols) < 3:
            continue
        tc.devices.append(TcDevice(
            interface=cols[0],
            in_bandwidth=cols[1] if cols[1] != "-" else "",
            out_bandwidth=cols[2] if cols[2] != "-" else "",
            options=cols[3].split(",") if len(cols) > 3 and cols[3] != "-" else [],
            redirect=cols[4] if len(cols) > 4 and cols[4] != "-" else "",
        ))

    for line in config.tcclasses:
        cols = line.columns
        if len(cols) < 4:
            continue
        try:
            mark = int(cols[1])
        except ValueError:
            continue
        tc.classes.append(TcClass(
            interface=cols[0],
            mark=mark,
            rate=cols[2],
            ceil=cols[3] if len(cols) > 3 and cols[3] != "-" else "",
            priority=int(cols[4]) if len(cols) > 4 and cols[4] != "-" else 1,
            options=cols[5].split(",") if len(cols) > 5 and cols[5] != "-" else [],
        ))

    for line in config.tcfilters:
        cols = line.columns
        if len(cols) < 1:
            continue
        tc.filters.append(TcFilter(
            tc_class=cols[0],
            source=cols[1] if len(cols) > 1 else "-",
            dest=cols[2] if len(cols) > 2 else "-",
            proto=cols[3] if len(cols) > 3 else "-",
            dport=cols[4] if len(cols) > 4 else "-",
            sport=cols[5] if len(cols) > 5 else "-",
            tos=cols[6] if len(cols) > 6 else "-",
            length=cols[7] if len(cols) > 7 else "-",
        ))

    return tc


def emit_tc_commands(tc: TcConfig) -> str:
    """Generate tc (traffic control) shell commands for QoS setup.

    These commands configure Linux kernel qdiscs and classes.
    They are NOT nft rules but complementary tc setup.
    """
    lines: list[str] = []
    lines.append("#!/bin/sh")
    lines.append("# Generated by shorewall-nft — tc/qdisc setup")
    lines.append("# Run this separately to configure traffic shaping")
    lines.append("")

    for dev in tc.devices:
        lines.append(f"# Device: {dev.interface}")
        if dev.out_bandwidth:
            lines.append(f"tc qdisc del dev {dev.interface} root 2>/dev/null")
            lines.append(f"tc qdisc add dev {dev.interface} root handle 1: htb default 1")
            lines.append(f"tc class add dev {dev.interface} parent 1: classid 1:1 htb rate {dev.out_bandwidth}")
        if dev.in_bandwidth:
            lines.append(f"tc qdisc del dev {dev.interface} ingress 2>/dev/null")
            lines.append(f"tc qdisc add dev {dev.interface} ingress")
        lines.append("")

    for cls in tc.classes:
        ceil = cls.ceil or cls.rate
        lines.append(f"tc class add dev {cls.interface} parent 1:1 classid 1:{cls.mark} htb rate {cls.rate} ceil {ceil} prio {cls.priority}")

    return "\n".join(lines)


def process_mangle(ir: FirewallIR, tcrules: list[ConfigLine],
                   mangle: list[ConfigLine], zones: ZoneModel) -> None:
    """Process mangle/tcrules into nft mark rules."""
    if not tcrules and not mangle:
        return

    if "mangle-prerouting" not in ir.chains:
        ir.add_chain(Chain(
            name="mangle-prerouting",
            chain_type=ChainType.ROUTE,
            hook=Hook.PREROUTING,
            priority=-150,
        ))

    for line in tcrules + mangle:
        _process_mark_rule(ir, line, zones)


def _process_mark_rule(ir: FirewallIR, line: ConfigLine,
                       zones: ZoneModel) -> None:
    """Process a single MARK/CONNMARK rule.

    tcrules format: MARK_VALUE SOURCE DEST PROTO PORT(S) ...
    mangle format:  ACTION SOURCE DEST PROTO PORT(S) ...
    """
    cols = line.columns
    if len(cols) < 2:
        return

    action = cols[0]
    source_spec = cols[1] if len(cols) > 1 else "-"
    dest_spec = cols[2] if len(cols) > 2 else "-"
    proto = cols[3] if len(cols) > 3 else None
    dport = cols[4] if len(cols) > 4 else None

    if proto == "-":
        proto = None
    if dport == "-":
        dport = None

    chain = ir.chains["mangle-prerouting"]
    rule = Rule(
        source_file=line.file,
        source_line=line.lineno,
    )

    if action.startswith("MARK("):
        mark_val = action[5:].rstrip(")")
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = f"mark:{mark_val}"
    elif action.startswith("CONNMARK("):
        mark_val = action[9:].rstrip(")")
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = f"connmark:{mark_val}"
    elif action.startswith("RESTORE"):
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = "restore_mark:"
    elif action.startswith("SAVE"):
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = "save_mark:"
    elif action.startswith("DSCP("):
        dscp_val = action[5:].rstrip(")")
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = f"dscp:{dscp_val}"
    elif action.startswith("CLASSIFY("):
        classify_val = action[9:].rstrip(")")
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = f"classify:{classify_val}"
    else:
        try:
            int(action, 0)
            rule.verdict = Verdict.ACCEPT
            rule.verdict_args = f"mark:{action}"
        except ValueError:
            return

    if source_spec and source_spec != "-":
        if ":" in source_spec:
            _, addr = source_spec.split(":", 1)
            if addr:
                rule.matches.append(Match(field="ip saddr", value=addr))

    if dest_spec and dest_spec != "-":
        if ":" in dest_spec:
            _, addr = dest_spec.split(":", 1)
            if addr:
                rule.matches.append(Match(field="ip daddr", value=addr))

    if proto:
        rule.matches.append(Match(field="meta l4proto", value=proto))
        if dport:
            rule.matches.append(Match(field=f"{proto} dport", value=dport))

    chain.rules.append(rule)
