"""Traffic Control / Mangle rule processing.

Handles:
- MARK, CONNMARK actions and tcrules/mangle files
- tcdevices, tcinterfaces, tcclasses, tcfilters, tcpri configs
- Translates to nft meta mark set / ct mark set statements

Note: nftables does not do tc/qdisc directly. TC shaping is handled
by setting marks in nft which are then used by tc qdiscs configured
separately. The tcdevices/tcclasses/tcfilters configs generate the
corresponding `tc` commands, not nft rules.

Native kernel apply path: ``apply_tc`` uses pyroute2 to configure
qdiscs/classes/filters directly via netlink — no tc(8) binary needed.
The ``emit_tc_commands`` / ``generate-tc`` bash-script path is kept as
a portable fallback.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from shorewall_nft.compiler.ir import (
    Chain,
    ChainType,
    FirewallIR,
    Hook,
    Match,
    Rule,
    Verdict,
    _expand_line_for_tokens,
)
from shorewall_nft.config.parser import ConfigLine
from shorewall_nft.config.zones import ZoneModel

logger = logging.getLogger("shorewall_nft.compiler.tc")


@dataclass
class TcDevice:
    """A traffic-controlled device."""
    interface: str
    in_bandwidth: str = ""
    out_bandwidth: str = ""
    options: list[str] = field(default_factory=list)
    redirect: str = ""


@dataclass
class TcClass:
    """A traffic class with rate/ceiling."""
    interface: str
    mark: int
    rate: str
    ceil: str = ""
    priority: int = 1
    options: list[str] = field(default_factory=list)


@dataclass
class TcFilter:
    """A filter to classify traffic into a TC class."""
    tc_class: str  # CLASS reference
    source: str = "-"
    dest: str = "-"
    proto: str = "-"
    dport: str = "-"
    sport: str = "-"
    tos: str = "-"
    length: str = "-"


@dataclass
class TcConfig:
    """Complete TC configuration."""
    devices: list[TcDevice] = field(default_factory=list)
    classes: list[TcClass] = field(default_factory=list)
    filters: list[TcFilter] = field(default_factory=list)


def parse_tc_config(config) -> TcConfig:
    """Parse TC config files into a TcConfig."""
    tc = TcConfig()

    for line in config.tcdevices:
        cols = line.columns
        if len(cols) < 3:
            continue
        tc.devices.append(TcDevice(
            interface=cols[0],
            in_bandwidth=cols[1] if cols[1] != "-" else "",
            out_bandwidth=cols[2] if cols[2] != "-" else "",
            options=cols[3].split(",") if len(cols) > 3 and cols[3] != "-" else [],
            redirect=cols[4] if len(cols) > 4 and cols[4] != "-" else "",
        ))

    for line in config.tcclasses:
        cols = line.columns
        if len(cols) < 4:
            continue
        try:
            mark = int(cols[1])
        except ValueError:
            continue
        tc.classes.append(TcClass(
            interface=cols[0],
            mark=mark,
            rate=cols[2],
            ceil=cols[3] if len(cols) > 3 and cols[3] != "-" else "",
            priority=int(cols[4]) if len(cols) > 4 and cols[4] != "-" else 1,
            options=cols[5].split(",") if len(cols) > 5 and cols[5] != "-" else [],
        ))

    for line in config.tcfilters:
        cols = line.columns
        if len(cols) < 1:
            continue
        tc.filters.append(TcFilter(
            tc_class=cols[0],
            source=cols[1] if len(cols) > 1 else "-",
            dest=cols[2] if len(cols) > 2 else "-",
            proto=cols[3] if len(cols) > 3 else "-",
            dport=cols[4] if len(cols) > 4 else "-",
            sport=cols[5] if len(cols) > 5 else "-",
            tos=cols[6] if len(cols) > 6 else "-",
            length=cols[7] if len(cols) > 7 else "-",
        ))

    return tc


def emit_tc_commands(tc: TcConfig) -> str:
    """Generate tc (traffic control) shell commands for QoS setup.

    These commands configure Linux kernel qdiscs and classes.
    They are NOT nft rules but complementary tc setup.
    """
    lines: list[str] = []
    lines.append("#!/bin/sh")
    lines.append("# Generated by shorewall-nft — tc/qdisc setup")
    lines.append("# Run this separately to configure traffic shaping")
    lines.append("")

    for dev in tc.devices:
        lines.append(f"# Device: {dev.interface}")
        if dev.out_bandwidth:
            lines.append(f"tc qdisc del dev {dev.interface} root 2>/dev/null")
            lines.append(f"tc qdisc add dev {dev.interface} root handle 1: htb default 1")
            lines.append(f"tc class add dev {dev.interface} parent 1: classid 1:1 htb rate {dev.out_bandwidth}")
        if dev.in_bandwidth:
            lines.append(f"tc qdisc del dev {dev.interface} ingress 2>/dev/null")
            lines.append(f"tc qdisc add dev {dev.interface} ingress")
        lines.append("")

    for cls in tc.classes:
        ceil = cls.ceil or cls.rate
        lines.append(f"tc class add dev {cls.interface} parent 1:1 classid 1:{cls.mark} htb rate {cls.rate} ceil {ceil} prio {cls.priority}")

    return "\n".join(lines)


@dataclass
class TcApplyResult:
    """Summary of a native TC apply operation via pyroute2."""
    applied: int
    failed: int
    errors: list[str]


def apply_tc(tc: TcConfig, *, netns: str | None = None) -> TcApplyResult:
    """Apply TC config via pyroute2.

    Configures kernel qdiscs, classes, and fwmark filters directly
    via netlink — no tc(8) binary required.  Opens
    ``IPRoute(netns=netns)`` when *netns* is set, otherwise uses the
    default (caller's) network namespace.

    Idempotence: qdiscs are deleted then re-added (same semantics as
    the bash script ``emit_tc_commands`` generates).  A
    ``NetlinkError`` with ``errno=ENOENT`` (2) during the delete step
    is silently ignored — the qdisc was simply not present yet.

    Returns a :class:`TcApplyResult` with counts of successfully
    applied and failed operations.  Failed operations are logged at
    WARNING level; no exception is raised.
    """
    try:
        from pyroute2 import IPRoute
        from pyroute2.netlink.exceptions import NetlinkError
    except ImportError:
        return TcApplyResult(
            applied=0, failed=0,
            errors=["pyroute2 not installed — cannot apply TC config natively"],
        )

    applied = 0
    failed = 0
    errors: list[str] = []

    def _record_error(msg: str) -> None:
        nonlocal failed
        failed += 1
        errors.append(msg)
        logger.warning("apply_tc: %s", msg)

    try:
        ipr: IPRoute = IPRoute(netns=netns) if netns else IPRoute()
    except Exception as ex:
        return TcApplyResult(
            applied=0, failed=0,
            errors=[f"IPRoute init failed: {ex}"],
        )

    # Cache interface name → index.
    iface_idx: dict[str, int] = {}

    def _idx(name: str) -> int | None:
        if name in iface_idx:
            return iface_idx[name]
        try:
            links = ipr.link_lookup(ifname=name)
        except NetlinkError:
            return None
        if not links:
            return None
        iface_idx[name] = links[0]
        return links[0]

    try:
        # ── Devices: root HTB qdisc (egress) and ingress qdisc ──────────
        for dev in tc.devices:
            idx = _idx(dev.interface)
            if idx is None:
                _record_error(
                    f"device {dev.interface!r}: interface not found, skipped")
                continue

            if dev.out_bandwidth:
                # Teardown existing root qdisc (idempotent).
                try:
                    ipr.tc("del", "htb", idx, 0x10000)
                except NetlinkError as ex:
                    if ex.code != 2:  # ENOENT → already absent
                        _record_error(
                            f"device {dev.interface!r}: "
                            f"del root qdisc failed: {ex}")
                        continue

                # Add HTB root qdisc: handle 1: default class 1.
                try:
                    ipr.tc("add", "htb", idx, 0x10000, default=1)
                except NetlinkError as ex:
                    _record_error(
                        f"device {dev.interface!r}: "
                        f"add root htb qdisc failed: {ex}")
                    continue

                # Add root class 1:1 with out_bandwidth as rate and ceil.
                try:
                    ipr.tc(
                        "add", "htb", idx,
                        handle=0x00010001,   # classid 1:1
                        parent=0x10000,      # parent 1:
                        rate=dev.out_bandwidth,
                        ceil=dev.out_bandwidth,
                        prio=0,
                    )
                    applied += 1
                except NetlinkError as ex:
                    _record_error(
                        f"device {dev.interface!r}: "
                        f"add root class 1:1 failed: {ex}")
                    continue

            if dev.in_bandwidth:
                # Teardown existing ingress qdisc (idempotent).
                try:
                    ipr.tc("del", "ingress", idx, 0xffff0000)
                except NetlinkError as ex:
                    if ex.code != 2:  # ENOENT → already absent
                        _record_error(
                            f"device {dev.interface!r}: "
                            f"del ingress qdisc failed: {ex}")
                        # Non-fatal; attempt add anyway.

                try:
                    ipr.tc("add", "ingress", idx, 0xffff0000)
                    applied += 1
                except NetlinkError as ex:
                    _record_error(
                        f"device {dev.interface!r}: "
                        f"add ingress qdisc failed: {ex}")

        # ── Classes: HTB leaf classes under root class 1:1 ──────────────
        for cls in tc.classes:
            idx = _idx(cls.interface)
            if idx is None:
                _record_error(
                    f"class {cls.interface!r}/{cls.mark}: "
                    f"interface not found, skipped")
                continue

            ceil = cls.ceil or cls.rate
            # classid 1:<mark>  parent 1:1
            classid = (1 << 16) | (cls.mark & 0xFFFF)
            parent = 0x00010001  # 1:1
            try:
                ipr.tc(
                    "add", "htb", idx,
                    handle=classid,
                    parent=parent,
                    rate=cls.rate,
                    ceil=ceil,
                    prio=cls.priority,
                )
                applied += 1
            except NetlinkError as ex:
                _record_error(
                    f"class {cls.interface!r}/{cls.mark}: "
                    f"add htb class failed: {ex}")

        # ── Filters: fwmark → classid mapping ───────────────────────────
        # Each TcFilter references a CLASS string like "eth0:1".
        # We add a fw (fwmark) filter: protocol ip parent 1:0 prio 1
        # handle <mark> fw classid 1:<mark>
        for flt in tc.filters:
            # Parse "INTERFACE:MARK" from tc_class field.
            if ":" not in flt.tc_class:
                _record_error(
                    f"filter class {flt.tc_class!r}: "
                    f"expected INTERFACE:MARK, skipped")
                continue
            iface_part, mark_part = flt.tc_class.rsplit(":", 1)
            try:
                mark_int = int(mark_part)
            except ValueError:
                _record_error(
                    f"filter class {flt.tc_class!r}: "
                    f"mark {mark_part!r} not an integer, skipped")
                continue

            idx = _idx(iface_part)
            if idx is None:
                _record_error(
                    f"filter {flt.tc_class!r}: "
                    f"interface {iface_part!r} not found, skipped")
                continue

            classid = (1 << 16) | (mark_int & 0xFFFF)
            # parent 1:0  (root qdisc handle, minor=0)
            parent = 0x10000
            try:
                ipr.tc(
                    "add-filter", "fw", idx,
                    parent=parent,
                    prio=1,
                    handle=mark_int,
                    classid=classid,
                )
                applied += 1
            except NetlinkError as ex:
                _record_error(
                    f"filter {flt.tc_class!r}: "
                    f"add fw filter failed: {ex}")

    finally:
        try:
            ipr.close()
        except Exception:
            pass

    return TcApplyResult(applied=applied, failed=failed, errors=errors)


def process_mangle(ir: FirewallIR, tcrules: list[ConfigLine],
                   mangle: list[ConfigLine], zones: ZoneModel) -> None:
    """Process mangle/tcrules into nft mark rules."""
    if not tcrules and not mangle:
        return

    if "mangle-prerouting" not in ir.chains:
        ir.add_chain(Chain(
            name="mangle-prerouting",
            chain_type=ChainType.ROUTE,
            hook=Hook.PREROUTING,
            priority=-150,
        ))

    for line in tcrules + mangle:
        _process_mark_rule(ir, line, zones)


def _process_mark_rule(ir: FirewallIR, line: ConfigLine,
                       zones: ZoneModel) -> None:
    """Process a single MARK/CONNMARK rule.

    tcrules format: MARK_VALUE SOURCE DEST PROTO PORT(S) ...
    mangle format:  ACTION SOURCE DEST PROTO PORT(S) ...

    SOURCE (col 1) and DEST (col 2) accept nfset:/dns:/dnsr: tokens.
    When tokens are present the rule is cloned for v4 and v6 families.
    """
    cols = line.columns
    if len(cols) < 2:
        return

    # nfset/dns/dnsr token pre-pass on SOURCE(col 1) + DEST(col 2).
    found, expanded = _expand_line_for_tokens(line, 1, 2, ir)
    if found:
        for exp_line in expanded:
            _process_mark_rule(ir, exp_line, zones)
        return

    action = cols[0]
    source_spec = cols[1] if len(cols) > 1 else "-"
    dest_spec = cols[2] if len(cols) > 2 else "-"
    proto = cols[3] if len(cols) > 3 else None
    dport = cols[4] if len(cols) > 4 else None

    if proto == "-":
        proto = None
    if dport == "-":
        dport = None

    chain = ir.chains["mangle-prerouting"]
    rule = Rule(
        source_file=line.file,
        source_line=line.lineno,
    )

    if action.startswith("MARK("):
        mark_val = action[5:].rstrip(")")
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = f"mark:{mark_val}"
    elif action.startswith("CONNMARK("):
        mark_val = action[9:].rstrip(")")
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = f"connmark:{mark_val}"
    elif action.startswith("RESTORE"):
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = "restore_mark:"
    elif action.startswith("SAVE"):
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = "save_mark:"
    elif action.startswith("DSCP("):
        dscp_val = action[5:].rstrip(")")
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = f"dscp:{dscp_val}"
    elif action.startswith("CLASSIFY("):
        classify_val = action[9:].rstrip(")")
        rule.verdict = Verdict.ACCEPT
        rule.verdict_args = f"classify:{classify_val}"
    else:
        try:
            int(action, 0)
            rule.verdict = Verdict.ACCEPT
            rule.verdict_args = f"mark:{action}"
        except ValueError:
            return

    if source_spec and source_spec != "-":
        # A rewritten set sentinel starts with '+'; use directly as addr.
        if source_spec.startswith("+") or source_spec.startswith("!+"):
            rule.matches.append(Match(field="ip saddr", value=source_spec))
        elif ":" in source_spec:
            _, addr = source_spec.split(":", 1)
            if addr:
                rule.matches.append(Match(field="ip saddr", value=addr))

    if dest_spec and dest_spec != "-":
        # A rewritten set sentinel starts with '+'; use directly as addr.
        if dest_spec.startswith("+") or dest_spec.startswith("!+"):
            rule.matches.append(Match(field="ip daddr", value=dest_spec))
        elif ":" in dest_spec:
            _, addr = dest_spec.split(":", 1)
            if addr:
                rule.matches.append(Match(field="ip daddr", value=addr))

    if proto:
        rule.matches.append(Match(field="meta l4proto", value=proto))
        if dport:
            rule.matches.append(Match(field=f"{proto} dport", value=dport))

    chain.rules.append(rule)
