#!/usr/bin/env python3
"""Merge per-standard security-test-plan Markdown fragments into one canonical file.

Usage:
    tools/merge-security-test-plan.py [--md-out PATH]

Reads all docs/testing/security-test-plan.<std>.md fragments and stitches them
together under a canonical structure.  The top-level '#' heading of each
fragment is demoted to '##'; section headings within each fragment are demoted
accordingly so the nesting is consistent.

The "Out of scope" sections from all fragments are also unified into a single
consolidated table at the end of the output document.
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ModuleNotFoundError:
    sys.exit("ERROR: pyyaml is not installed. Run: pip install pyyaml")


# ---------------------------------------------------------------------------
# Fragment ordering (same as YAML merger)
# ---------------------------------------------------------------------------

_FRAGMENTS = [
    {
        "md_file": "security-test-plan.cc.md",
        "yaml_file": "security-test-plan.cc.yaml",
        "anchor": "common-criteria",
        "toc_label": "Common Criteria (ISO/IEC 15408)",
        "std_short": "CC",
    },
    {
        "md_file": "security-test-plan.nist.md",
        "yaml_file": "security-test-plan.nist.yaml",
        "anchor": "nist-sp-800-53",
        "toc_label": "NIST SP 800-53",
        "std_short": "NIST",
    },
    {
        "md_file": "security-test-plan.bsi.md",
        "yaml_file": "security-test-plan.bsi.yaml",
        "anchor": "bsi-it-grundschutz",
        "toc_label": "BSI IT-Grundschutz",
        "std_short": "BSI",
    },
    {
        "md_file": "security-test-plan.cis.md",
        "yaml_file": "security-test-plan.cis.yaml",
        "anchor": "cis-benchmarks",
        "toc_label": "CIS Benchmarks",
        "std_short": "CIS",
    },
    {
        "md_file": "security-test-plan.owasp.md",
        "yaml_file": "security-test-plan.owasp.yaml",
        "anchor": "owasp",
        "toc_label": "OWASP",
        "std_short": "OWASP",
    },
    {
        "md_file": "security-test-plan.iso27001.md",
        "yaml_file": "security-test-plan.iso27001.yaml",
        "anchor": "iso-27001",
        "toc_label": "ISO/IEC 27001",
        "std_short": "ISO-27001",
    },
    {
        "md_file": "security-test-plan.ipv6-perf.md",
        "yaml_file": "security-test-plan.ipv6-perf.yaml",
        "anchor": "performance-addendum-ipv6",
        "toc_label": "Performance addendum (IPv6)",
        "std_short": "Perf-IPv6",
    },
]


def _demote_headings(text: str, levels: int = 1) -> str:
    """Demote all Markdown ATX headings by *levels* levels."""
    def _replace(m: re.Match) -> str:
        hashes = m.group(1)
        rest = m.group(2)
        new_hashes = "#" * (len(hashes) + levels)
        return f"{new_hashes}{rest}"

    return re.sub(r"^(#+)( .+)$", _replace, text, flags=re.MULTILINE)


def _strip_generator_comment(text: str) -> str:
    """Remove the top 'Merged by M1' or similar comment lines."""
    lines = text.splitlines(keepends=True)
    result = []
    skip_intro = True
    for line in lines:
        if skip_intro:
            stripped = line.strip()
            # Skip blank lines and lines like "Merged by M1 into ..."
            if not stripped or re.match(
                r"(merged by m1|generated by|auto-generated|do not edit)", stripped, re.I
            ):
                continue
            skip_intro = False
        result.append(line)
    return "".join(result)


def _extract_out_of_scope_from_yaml(path: Path, std_short: str) -> list[tuple[str, str, str]]:
    """Return list of (standard, item, reason) from a YAML fragment's out_of_scope list."""
    if not path.exists():
        return []
    try:
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return []

    rows = []
    for entry in doc.get("out_of_scope", []):
        item = (
            entry.get("item")
            or entry.get("sfr_family")
            or entry.get("control_family")
            or entry.get("control")
            or entry.get("test_id")
            or entry.get("id")
            or "—"
        )
        reason = entry.get("reason", "").strip()
        if reason:
            rows.append((std_short, item, reason))
    return rows


def merge(catalogue_dir: Path, out_path: Path) -> None:
    generated_at = datetime.now(tz=timezone.utc).isoformat(timespec="seconds")

    # --- Build table of contents ---
    toc_lines = []
    for frag in _FRAGMENTS:
        fpath = catalogue_dir / frag["md_file"]
        if fpath.exists():
            toc_lines.append(
                f"- [{frag['toc_label']}](#{frag['anchor']})"
            )
    toc_lines.append("- [Consolidated out of scope](#consolidated-out-of-scope)")
    toc_lines.append("- [How to run](#how-to-run)")

    # --- Build body sections ---
    body_sections: list[str] = []
    oos_rows: list[tuple[str, str, str]] = []  # (std, item, reason)

    for frag in _FRAGMENTS:
        fpath = catalogue_dir / frag["md_file"]
        yfpath = catalogue_dir / frag["yaml_file"]

        if not fpath.exists():
            print(f"WARNING: fragment not found: {fpath}", file=sys.stderr)
            continue

        raw = fpath.read_text(encoding="utf-8")
        # Demote all headings by 1 so fragment's '#' becomes '##'
        demoted = _demote_headings(raw, levels=1)
        # Strip first line if it's a level-1 heading (now demoted to ##)
        lines = demoted.splitlines(keepends=True)
        # Find and rename the top-level (now ##) heading to use the anchor label
        replaced_title = False
        result_lines = []
        for line in lines:
            if not replaced_title and line.startswith("## "):
                # Replace with canonical section heading + anchor
                result_lines.append(
                    f"## {frag['toc_label']} {{#{frag['anchor']}}}\n"
                )
                replaced_title = True
                continue
            result_lines.append(line)
        section_text = "".join(result_lines)

        body_sections.append(section_text.rstrip() + "\n")

        # Collect out-of-scope rows from YAML
        oos_rows.extend(_extract_out_of_scope_from_yaml(yfpath, frag["std_short"]))

    # --- Build consolidated out-of-scope table ---
    oos_table_lines = [
        "## Consolidated out of scope {#consolidated-out-of-scope}\n",
        "\n",
        "Every fragment's out-of-scope items unified:\n",
        "\n",
        "| Standard | Item | Reason |\n",
        "|---|---|---|\n",
    ]
    for std, item, reason in oos_rows:
        # Clean up multi-line reasons
        clean_reason = " ".join(reason.split())
        oos_table_lines.append(f"| {std} | {item} | {clean_reason} |\n")

    # --- How to run section ---
    how_to_run = """\
## How to run {#how-to-run}

End-to-end executor:

```bash
tools/run-security-test-plan.sh --standards all --config <base-config.yaml>
```

Filter to a subset of standards:

```bash
tools/run-security-test-plan.sh --standards cis,owasp --config <base-config.yaml>
```

Dry-run (print planned invocations without executing):

```bash
tools/run-security-test-plan.sh --standards all --config <base-config.yaml> --dry-run
```

See `tools/run-security-test-plan.sh --help` for full options.

The machine-readable catalogue is at `docs/testing/security-test-plan.yaml`.
Regenerate this document and the YAML catalogue:

```bash
tools/merge-security-test-plan-yaml.py
tools/merge-security-test-plan.py
```
"""

    # --- Assemble output ---
    header = f"""\
# Firewall Security Test Plan

Auto-generated canonical document. Generated at {generated_at}.
Do NOT edit by hand; update source fragments under
`docs/testing/security-test-plan.<std>.md` and re-run
`tools/merge-security-test-plan.py`.

## Table of contents

{chr(10).join(toc_lines)}

"""

    output_parts = [header]
    for sec in body_sections:
        output_parts.append(sec)
        output_parts.append("\n---\n\n")

    output_parts.append("".join(oos_table_lines))
    output_parts.append("\n---\n\n")
    output_parts.append(how_to_run)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(output_parts), encoding="utf-8")
    print(
        f"Wrote consolidated security-test-plan.md ({len(body_sections)} sections, "
        f"{len(oos_rows)} out-of-scope rows) -> {out_path}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Merge per-standard Markdown fragments into security-test-plan.md"
    )
    parser.add_argument(
        "--md-out",
        metavar="PATH",
        default=None,
        help=(
            "Output path for the merged Markdown "
            "(default: docs/testing/security-test-plan.md relative to repo root)"
        ),
    )
    parser.add_argument(
        "--catalogue-dir",
        metavar="DIR",
        default=None,
        help="Directory containing the fragment files (default: docs/testing/ relative to repo root)",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    catalogue_dir = Path(args.catalogue_dir) if args.catalogue_dir else repo_root / "docs" / "testing"
    out_path = Path(args.md_out) if args.md_out else catalogue_dir / "security-test-plan.md"

    merge(catalogue_dir, out_path)


if __name__ == "__main__":
    main()
