#!/bin/sh
# setup-remote-test-host.sh — deploy shorewall-nft to a RAM-only test box.
#
# Bootstraps a disposable test host over SSH:
#   1. rsyncs the working copy to /root/shorewall-nft (excluding .venv, caches)
#   2. creates a venv and `pip install -e .`
#   3. runs tools/install-test-tooling.sh for the run-netns wrapper + sudoers
#   4. copies the marcant-fw iptables-save dump + matching shorewall config
#      to /root/simulate-data, so `shorewall-nft simulate` has ground truth
#
# Usage:
#   tools/setup-remote-test-host.sh root@192.0.2.83
#   tools/setup-remote-test-host.sh root@host --simulate-src /path/to/old
#
# The host must already accept passwordless SSH for the given user.
# Idempotent: safe to re-run after the box is re-imaged.

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SIMULATE_SRC_DEFAULT="$REPO_DIR/../old"
SIMULATE_SRC="$SIMULATE_SRC_DEFAULT"
DEPLOY_ENV_DEFAULT="$SCRIPT_DIR/marcant-deploy.env"
DEPLOY_ENV="$DEPLOY_ENV_DEFAULT"
REMOTE=""

while [ $# -gt 0 ]; do
    case "$1" in
        --simulate-src) SIMULATE_SRC="$2"; shift 2 ;;
        --deploy-env)   DEPLOY_ENV="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            if [ -z "$REMOTE" ]; then
                REMOTE="$1"
                shift
            else
                echo "unexpected argument: $1" >&2
                exit 1
            fi
            ;;
    esac
done

[ -n "$REMOTE" ] || { echo "usage: $0 user@host [--simulate-src DIR]" >&2; exit 1; }

info() { printf 'setup-remote-test-host: %s\n' "$1"; }

info "rsync repo → $REMOTE:/root/shorewall-nft"
ssh "$REMOTE" 'mkdir -p /root/shorewall-nft'
rsync -a --delete \
    --exclude='.git' \
    --exclude='__pycache__' \
    --exclude='.pytest_cache' \
    --exclude='.ruff_cache' \
    --exclude='dist' \
    --exclude='*.egg-info' \
    --exclude='.venv' \
    --exclude='tools/marcant-deploy.env' \
    "$REPO_DIR/" "$REMOTE:/root/shorewall-nft/"

info "install apt deps (idempotent)"
ssh "$REMOTE" 'DEBIAN_FRONTEND=noninteractive apt-get update -qq >/dev/null 2>&1 || true; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3 python3-venv python3-pip python3.12-venv \
    python3-pytest python3-pytest-xdist python3-click python3-pyroute2 \
    iproute2 sudo nftables conntrack ipset 2>&1 | tail -5 || true'

info "create venv + editable install"
ssh "$REMOTE" 'cd /root/shorewall-nft && \
    python3 -m venv --system-site-packages .venv && \
    .venv/bin/pip install -q -e . && \
    .venv/bin/shorewall-nft --version'

info "run install-test-tooling.sh on remote"
ssh "$REMOTE" 'sh /root/shorewall-nft/tools/install-test-tooling.sh'

if [ -f "$SIMULATE_SRC/iptables.txt" ] && [ -d "$SIMULATE_SRC/etc/shorewall" ]; then
    info "copy simulate ground truth from $SIMULATE_SRC"
    ssh "$REMOTE" 'mkdir -p /root/simulate-data/etc'
    rsync -a "$SIMULATE_SRC/etc/shorewall/" "$REMOTE:/root/simulate-data/etc/shorewall/"
    if [ -d "$SIMULATE_SRC/etc/shorewall6" ]; then
        rsync -a "$SIMULATE_SRC/etc/shorewall6/" "$REMOTE:/root/simulate-data/etc/shorewall6/"
    fi
    rsync "$SIMULATE_SRC/iptables.txt" "$REMOTE:/root/simulate-data/iptables.txt"
    # fw-state dumps used by simlab
    for f in ip4add ip4routes ip6add ip6routes; do
        if [ -f "$SIMULATE_SRC/$f" ]; then
            rsync "$SIMULATE_SRC/$f" "$REMOTE:/root/simulate-data/$f"
        fi
    done
    info "simulate data in /root/simulate-data/ (config + iptables.txt + fw-state dumps)"
else
    info "WARNING: no simulate ground truth at $SIMULATE_SRC — skipping"
    info "         (expected: $SIMULATE_SRC/iptables.txt + $SIMULATE_SRC/etc/shorewall/)"
fi

if [ -f "$DEPLOY_ENV" ]; then
    info "source $DEPLOY_ENV and deploy plugins/netbox.{toml,token}"
    # shellcheck disable=SC1090
    . "$DEPLOY_ENV"
    : "${NETBOX_URL:?NETBOX_URL not set in $DEPLOY_ENV}"
    : "${NETBOX_TOKEN:?NETBOX_TOKEN not set in $DEPLOY_ENV}"
    NETBOX_CACHE_TTL="${NETBOX_CACHE_TTL:-86400}"
    NETBOX_TIMEOUT="${NETBOX_TIMEOUT:-30}"
    NETBOX_DIRTY_FLUSH_INTERVAL="${NETBOX_DIRTY_FLUSH_INTERVAL:-50}"
    NETBOX_PRIORITY="${NETBOX_PRIORITY:-100}"
    NETBOX_BULK_SUBNETS="${NETBOX_BULK_SUBNETS:-}"

    # Assemble the TOML list literal from the space-separated env var.
    nb_subnets_toml="["
    for s in $NETBOX_BULK_SUBNETS; do
        nb_subnets_toml="${nb_subnets_toml}\"$s\", "
    done
    nb_subnets_toml="${nb_subnets_toml%, }]"

    ssh "$REMOTE" "mkdir -p /etc/shorewall46/plugins /root/simulate-data/etc/shorewall/plugins"

    # plugins.conf (enable netbox)
    ssh "$REMOTE" "cat > /etc/shorewall46/plugins.conf" <<'EOF'
# shorewall-nft plugins.conf — generated by setup-remote-test-host.sh

[[plugins]]
name = "netbox"
enabled = true
EOF

    # netbox.toml (public config)
    ssh "$REMOTE" "cat > /etc/shorewall46/plugins/netbox.toml" <<EOF
# Generated by setup-remote-test-host.sh from tools/marcant-deploy.env.
# Do not hand-edit on the test host — changes get overwritten on redeploy.

url = "$NETBOX_URL"
token_file = "/etc/shorewall46/plugins/netbox.token"

priority = $NETBOX_PRIORITY
cache_ttl = $NETBOX_CACHE_TTL
timeout = $NETBOX_TIMEOUT
dirty_flush_interval = $NETBOX_DIRTY_FLUSH_INTERVAL

bulk_subnets = $nb_subnets_toml
EOF

    # netbox.token (secret)
    ssh "$REMOTE" "umask 077 && printf '%s\n' \"$NETBOX_TOKEN\" > /etc/shorewall46/plugins/netbox.token && chmod 600 /etc/shorewall46/plugins/netbox.token"

    # Mirror into /root/simulate-data/etc/shorewall/ so a fresh
    # simlab bootstrap from that source tree gets them too. Guard
    # against the (common) case where /etc/shorewall46 is already a
    # symlink into /root/simulate-data/etc/shorewall — cp -u would
    # otherwise complain "same file".
    ssh "$REMOTE" 'if [ "$(readlink -f /etc/shorewall46)" != "$(readlink -f /root/simulate-data/etc/shorewall)" ]; then cp /etc/shorewall46/plugins.conf /root/simulate-data/etc/shorewall/plugins.conf && cp /etc/shorewall46/plugins/netbox.toml /root/simulate-data/etc/shorewall/plugins/netbox.toml && cp /etc/shorewall46/plugins/netbox.token /root/simulate-data/etc/shorewall/plugins/netbox.token && chmod 600 /root/simulate-data/etc/shorewall/plugins/netbox.token; fi'

    info "plugins deployed: /etc/shorewall46/plugins.conf + plugins/netbox.{toml,token}"
else
    info "no deploy env at $DEPLOY_ENV — skipping plugin deploy"
    info "  (copy tools/marcant-deploy.env.example → tools/marcant-deploy.env and fill it in)"
fi

# ──────────────────────────────────────────────────────────────────
# Produce /etc/shorewall46 by merging v4 + v6 sources through the
# plugin pipeline. This is the step that actually runs the netbox
# plugin (for IPv4↔IPv6 pairing / translation-rule enrichment).
# ──────────────────────────────────────────────────────────────────
info "merge-config: /root/simulate-data/etc/shorewall{,6} → /etc/shorewall46 (plugin-aware)"
ssh "$REMOTE" '
set -e
if [ -d /etc/shorewall46 ] && [ ! -L /etc/shorewall46 ]; then
    rm -rf /etc/shorewall46
fi
if [ -L /etc/shorewall46 ]; then
    rm -f /etc/shorewall46
fi
if [ -d /root/simulate-data/etc/shorewall6 ]; then
    /root/shorewall-nft/.venv/bin/shorewall-nft merge-config \
        /root/simulate-data/etc/shorewall \
        /root/simulate-data/etc/shorewall6 \
        -o /etc/shorewall46
else
    /root/shorewall-nft/.venv/bin/shorewall-nft merge-config \
        /root/simulate-data/etc/shorewall \
        -o /etc/shorewall46
fi
# Re-apply plugin files into the merged output (merge-config may
# not carry plugins.conf + plugins/ forward from either source).
mkdir -p /etc/shorewall46/plugins
if [ -f /root/simulate-data/etc/shorewall/plugins.conf ]; then
    cp /root/simulate-data/etc/shorewall/plugins.conf /etc/shorewall46/plugins.conf
fi
if [ -d /root/simulate-data/etc/shorewall/plugins ]; then
    cp -a /root/simulate-data/etc/shorewall/plugins/. /etc/shorewall46/plugins/
    chmod 600 /etc/shorewall46/plugins/netbox.token 2>/dev/null || true
fi
echo "merged: $(find /etc/shorewall46 -maxdepth 1 -type f | wc -l) files"
'

info "done. next steps on the remote:"
info "  systemd-run --unit=shorewall-pytest --collect --working-directory=/root/shorewall-nft \\"
info "    --property=StandardOutput=file:/tmp/pytest.log \\"
info "    --property=StandardError=file:/tmp/pytest.log \\"
info "    /root/shorewall-nft/.venv/bin/python -m pytest tests/ -v"
info "  /root/shorewall-nft/.venv/bin/shorewall-nft simulate /root/simulate-data/etc/shorewall \\"
info "    --iptables /root/simulate-data/iptables.txt -n 60"
