# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npeer.proto\x12\nshorewalld\"\xb1\x02\n\x0cPeerEnvelope\x12\x0b\n\x03seq\x18\x01 \x02(\x04\x12\x12\n\nts_unix_ns\x18\x02 \x02(\x04\x12\x13\n\x0borigin_node\x18\x03 \x02(\t\x12\x15\n\rproto_version\x18\x04 \x02(\r\x12)\n\tdns_batch\x18\n \x01(\x0b\x32\x14.shorewalld.DnsBatchH\x00\x12*\n\theartbeat\x18\x0b \x01(\x0b\x32\x15.shorewalld.HeartbeatH\x00\x12\x37\n\x10snapshot_request\x18\x0c \x01(\x0b\x32\x1b.shorewalld.SnapshotRequestH\x00\x12\x39\n\x11snapshot_response\x18\r \x01(\x0b\x32\x1c.shorewalld.SnapshotResponseH\x00\x42\t\n\x07payload\"2\n\x08\x44nsBatch\x12&\n\x07updates\x18\x01 \x03(\x0b\x32\x15.shorewalld.DnsUpdate\"W\n\tDnsUpdate\x12\r\n\x05qname\x18\x01 \x02(\t\x12\r\n\x05\x61_rrs\x18\x02 \x03(\x0c\x12\x10\n\x08\x61\x61\x61\x61_rrs\x18\x03 \x03(\x0c\x12\x0b\n\x03ttl\x18\x04 \x02(\r\x12\r\n\x05rcode\x18\x05 \x01(\r\"\xa6\x01\n\tHeartbeat\x12\x1d\n\x15\x66rames_accepted_total\x18\x01 \x02(\x04\x12\x1c\n\x14\x66rames_dropped_total\x18\x02 \x02(\x04\x12\x13\n\x0bqueue_depth\x18\x03 \x02(\r\x12\x1e\n\x16nft_set_elements_total\x18\x04 \x02(\r\x12\x16\n\x0euptime_seconds\x18\x05 \x02(\r\x12\x0f\n\x07version\x18\x06 \x02(\t\"<\n\x0fSnapshotRequest\x12\x13\n\x0bsnapshot_id\x18\x01 \x02(\x04\x12\x14\n\x0cqname_filter\x18\x02 \x03(\t\"y\n\x10SnapshotResponse\x12\x13\n\x0bsnapshot_id\x18\x01 \x02(\x04\x12\x13\n\x0b\x63hunk_index\x18\x02 \x02(\r\x12\x14\n\x0ctotal_chunks\x18\x03 \x02(\r\x12%\n\x07\x65ntries\x18\x04 \x03(\x0b\x32\x14.shorewalld.SetEntry\"L\n\x08SetEntry\x12\r\n\x05qname\x18\x01 \x02(\t\x12\x0e\n\x06\x66\x61mily\x18\x02 \x02(\r\x12\n\n\x02ip\x18\x03 \x02(\x0c\x12\x15\n\rremaining_ttl\x18\x04 \x02(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PEERENVELOPE._serialized_start=27
  _PEERENVELOPE._serialized_end=332
  _DNSBATCH._serialized_start=334
  _DNSBATCH._serialized_end=384
  _DNSUPDATE._serialized_start=386
  _DNSUPDATE._serialized_end=473
  _HEARTBEAT._serialized_start=476
  _HEARTBEAT._serialized_end=642
  _SNAPSHOTREQUEST._serialized_start=644
  _SNAPSHOTREQUEST._serialized_end=704
  _SNAPSHOTRESPONSE._serialized_start=706
  _SNAPSHOTRESPONSE._serialized_end=827
  _SETENTRY._serialized_start=829
  _SETENTRY._serialized_end=905
# @@protoc_insertion_point(module_scope)
