"""
Unit tests for shorewall_nft.verify.iptables_parser.

All fixtures are inline multi-line strings — no external files, no root,
no netns.
"""
from __future__ import annotations

import textwrap
from pathlib import Path

import pytest

from shorewall_nft.verify.iptables_parser import Rule, Table, parse_iptables_save


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def write_dump(tmp_path: Path, content: str) -> Path:
    """Write a fixture string to a temp file and return its Path."""
    p = tmp_path / "iptables.txt"
    p.write_text(textwrap.dedent(content), encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# Fixtures as module-level strings
# ---------------------------------------------------------------------------

MINIMAL_FILTER = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -j ACCEPT
COMMIT
"""

MULTI_TABLE = """\
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
-A INPUT -j ACCEPT
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 192.0.2.10:8080
COMMIT
"""

CHAIN_POLICIES = """\
*filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT DROP [123:456]
COMMIT
"""

NEGATION_RULE = """\
*filter
:FORWARD ACCEPT [0:0]
-A FORWARD ! -i eth0 -j ACCEPT
COMMIT
"""

SRC_DST_RULE = """\
*filter
:FORWARD ACCEPT [0:0]
-A FORWARD -s 192.0.2.0/24 -d 198.51.100.0/24 -j ACCEPT
COMMIT
"""

PORT_MATCH_RULE = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --dport 22 -j ACCEPT
COMMIT
"""

COMMENT_RULE = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -m comment --comment "ssh from admin" -j ACCEPT
COMMIT
"""

MULTIPORT_RULE = """\
*filter
:FORWARD ACCEPT [0:0]
-A FORWARD -p tcp --dports 80,443 -j ACCEPT
COMMIT
"""

IPV6_ADDR_RULE = """\
*filter
:FORWARD ACCEPT [0:0]
-A FORWARD -s 2001:db8::/32 -j ACCEPT
COMMIT
"""

SNAT_RULE = """\
*nat
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 10.0.0.0/8 -o eth0 -j SNAT --to-source 203.0.113.1
COMMIT
"""

NOTRACK_RULE = """\
*raw
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p udp --dport 514 -j CT --notrack
COMMIT
"""

IPRANGE_RULE = """\
*filter
:FORWARD ACCEPT [0:0]
-A FORWARD -m iprange --src-range 203.0.113.220-203.0.113.254 -j ACCEPT
COMMIT
"""

COMMENTS_AND_BLANK_LINES = """\
# Generated by iptables-save v1.8.9
*filter
:INPUT ACCEPT [0:0]

# a blank line above and a comment
-A INPUT -j ACCEPT
COMMIT
"""

GOTO_RULE = """\
*filter
:INPUT ACCEPT [0:0]
:log_drop - [0:0]
-A INPUT -g log_drop
COMMIT
"""


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestMinimalHappyPath:
    def test_returns_dict_of_tables(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, MINIMAL_FILTER))
        assert isinstance(tables, dict)
        assert "filter" in tables

    def test_table_is_Table_instance(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, MINIMAL_FILTER))
        assert isinstance(tables["filter"], Table)

    def test_single_rule_parsed(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, MINIMAL_FILTER))
        rules = tables["filter"].rules["INPUT"]
        assert len(rules) == 1
        assert isinstance(rules[0], Rule)
        assert rules[0].target == "ACCEPT"

    def test_rule_raw_preserved(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, MINIMAL_FILTER))
        rule = tables["filter"].rules["INPUT"][0]
        assert rule.raw == "-A INPUT -j ACCEPT"


class TestMultipleTables:
    def test_both_tables_present(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, MULTI_TABLE))
        assert "filter" in tables
        assert "nat" in tables

    def test_filter_rule_in_filter_only(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, MULTI_TABLE))
        assert "INPUT" in tables["filter"].rules
        assert "INPUT" not in tables["nat"].rules

    def test_nat_rule_in_nat_only(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, MULTI_TABLE))
        assert "PREROUTING" in tables["nat"].rules
        assert "PREROUTING" not in tables["filter"].rules

    def test_nat_rule_target_and_args(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, MULTI_TABLE))
        rule = tables["nat"].rules["PREROUTING"][0]
        assert rule.target == "DNAT"
        assert rule.target_args.get("to-destination") == "192.0.2.10:8080"


class TestChainPolicies:
    def test_drop_policy_captured(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, CHAIN_POLICIES))
        assert tables["filter"].chains["INPUT"]["policy"] == "DROP"

    def test_accept_policy_captured(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, CHAIN_POLICIES))
        assert tables["filter"].chains["FORWARD"]["policy"] == "ACCEPT"

    def test_counters_captured(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, CHAIN_POLICIES))
        assert tables["filter"].chains["OUTPUT"]["counters"] == "[123:456]"

    def test_chain_with_no_rules_initialised(self, tmp_path):
        # Chain declarations must initialise the rule list even when no
        # -A lines appear for that chain.
        tables = parse_iptables_save(write_dump(tmp_path, CHAIN_POLICIES))
        assert tables["filter"].rules["INPUT"] == []


class TestNegation:
    def test_negated_iif_rule_is_parsed(self, tmp_path):
        # `-A FORWARD ! -i eth0 -j ACCEPT` — the "!" precedes the flag.
        # shlex splits this as ['!', '-i', 'eth0', ...].  The parser skips
        # the standalone '!' token (not in _FLAG_TO_KEY, not -m/-j/-g) and
        # then reads -i with value 'eth0' — so the negation marker is lost.
        # This is the current documented behaviour; the raw line still
        # preserves it for diagnostic use.
        tables = parse_iptables_save(write_dump(tmp_path, NEGATION_RULE))
        rule = tables["filter"].rules["FORWARD"][0]
        assert rule.iif is not None

    def test_negated_iif_raw_line_preserved(self, tmp_path):
        # Even though the negation is lost from matches, the raw line keeps it.
        tables = parse_iptables_save(write_dump(tmp_path, NEGATION_RULE))
        rule = tables["filter"].rules["FORWARD"][0]
        assert "!" in rule.raw

    def test_post_flag_negation_stored_with_bang(self, tmp_path):
        # When negation appears AFTER the flag ("-i ! eth0"), the parser
        # detects the "!" as the value token and prepends it: "!eth0".
        dump = """\
*filter
:FORWARD ACCEPT [0:0]
-A FORWARD -i ! eth0 -j ACCEPT
COMMIT
"""
        tables = parse_iptables_save(write_dump(tmp_path, dump))
        rule = tables["filter"].rules["FORWARD"][0]
        assert rule.iif == "!eth0"


class TestSrcDst:
    def test_saddr_parsed(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, SRC_DST_RULE))
        rule = tables["filter"].rules["FORWARD"][0]
        assert rule.saddr == "192.0.2.0/24"

    def test_daddr_parsed(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, SRC_DST_RULE))
        rule = tables["filter"].rules["FORWARD"][0]
        assert rule.daddr == "198.51.100.0/24"


class TestPortMatch:
    def test_proto_parsed(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, PORT_MATCH_RULE))
        rule = tables["filter"].rules["INPUT"][0]
        assert rule.proto == "tcp"

    def test_dport_parsed(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, PORT_MATCH_RULE))
        rule = tables["filter"].rules["INPUT"][0]
        assert rule.dport == "22"


class TestComment:
    def test_comment_text_preserved(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, COMMENT_RULE))
        rule = tables["filter"].rules["INPUT"][0]
        assert rule.comment == "ssh from admin"

    def test_target_still_parsed_with_comment(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, COMMENT_RULE))
        rule = tables["filter"].rules["INPUT"][0]
        assert rule.target == "ACCEPT"


class TestMultiport:
    def test_dports_stored_under_dport_key(self, tmp_path):
        # --dports is aliased to the same 'dport' key as --dport.
        tables = parse_iptables_save(write_dump(tmp_path, MULTIPORT_RULE))
        rule = tables["filter"].rules["FORWARD"][0]
        assert rule.dport == "80,443"


class TestIPv6Address:
    def test_ipv6_saddr_parsed(self, tmp_path):
        # The parser makes no distinction between IPv4 and IPv6 addresses;
        # it stores whatever string follows -s / --source.
        tables = parse_iptables_save(write_dump(tmp_path, IPV6_ADDR_RULE))
        rule = tables["filter"].rules["FORWARD"][0]
        assert rule.saddr == "2001:db8::/32"


class TestSnat:
    def test_snat_target(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, SNAT_RULE))
        rule = tables["nat"].rules["POSTROUTING"][0]
        assert rule.target == "SNAT"

    def test_snat_to_source_arg(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, SNAT_RULE))
        rule = tables["nat"].rules["POSTROUTING"][0]
        assert rule.target_args.get("to-source") == "203.0.113.1"

    def test_snat_oif(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, SNAT_RULE))
        rule = tables["nat"].rules["POSTROUTING"][0]
        assert rule.oif == "eth0"


class TestNotrack:
    def test_ct_notrack_parsed(self, tmp_path):
        # NOTRACK via `-j CT --notrack`; the flag value is empty string.
        tables = parse_iptables_save(write_dump(tmp_path, NOTRACK_RULE))
        rule = tables["raw"].rules["PREROUTING"][0]
        assert rule.target == "CT"
        assert "notrack" in rule.target_args


class TestIprange:
    def test_src_range_stored_as_saddr(self, tmp_path):
        # -m iprange --src-range is normalised into the saddr key so
        # verifiers can compare it uniformly.
        tables = parse_iptables_save(write_dump(tmp_path, IPRANGE_RULE))
        rule = tables["filter"].rules["FORWARD"][0]
        assert rule.saddr == "203.0.113.220-203.0.113.254"


class TestCommentsAndBlankLines:
    def test_hash_comments_ignored(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, COMMENTS_AND_BLANK_LINES))
        # Only one rule should appear — the -A line.
        assert len(tables["filter"].rules["INPUT"]) == 1

    def test_blank_lines_ignored(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, COMMENTS_AND_BLANK_LINES))
        assert "filter" in tables


class TestCommitMarker:
    def test_commit_does_not_produce_a_rule(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, MINIMAL_FILTER))
        # If COMMIT were parsed as a rule, INPUT would have 2 entries or
        # there would be a stray 'COMMIT' chain.
        assert "COMMIT" not in tables["filter"].rules
        assert len(tables["filter"].rules["INPUT"]) == 1

    def test_commit_resets_table_context(self, tmp_path):
        # Rules after COMMIT but before the next *table marker should be
        # silently ignored (current is set to None by COMMIT).
        dump = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -j ACCEPT
COMMIT
-A INPUT -j DROP
"""
        tables = parse_iptables_save(write_dump(tmp_path, dump))
        # The stray -A line after COMMIT must not be parsed.
        assert len(tables["filter"].rules["INPUT"]) == 1

    def test_multi_table_commit_separates_tables(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, MULTI_TABLE))
        # filter rules must not bleed into nat and vice versa.
        assert "PREROUTING" not in tables["filter"].rules
        assert "INPUT" not in tables["nat"].rules


class TestGotoFlag:
    def test_goto_target_parsed(self, tmp_path):
        # -g TARGET is a "goto" (non-returning jump); we treat it the same
        # as -j for target classification purposes.
        tables = parse_iptables_save(write_dump(tmp_path, GOTO_RULE))
        rule = tables["filter"].rules["INPUT"][0]
        assert rule.target == "log_drop"


class TestMalformedInput:
    def test_missing_file_raises_file_not_found(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            parse_iptables_save(tmp_path / "nonexistent.txt")

    def test_rule_outside_table_ignored(self, tmp_path):
        # -A lines that appear before any *table header have no current
        # table; they should be silently skipped.
        dump = """\
-A INPUT -j ACCEPT
*filter
:INPUT ACCEPT [0:0]
COMMIT
"""
        tables = parse_iptables_save(write_dump(tmp_path, dump))
        assert tables["filter"].rules["INPUT"] == []

    def test_empty_file_returns_empty_dict(self, tmp_path):
        tables = parse_iptables_save(write_dump(tmp_path, ""))
        assert tables == {}

    def test_only_comments_and_blanks_returns_empty(self, tmp_path):
        dump = """\
# just a comment

# another comment
"""
        tables = parse_iptables_save(write_dump(tmp_path, dump))
        assert tables == {}
